config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/mngmnt', :as => 'rails_admin'
  mount API => "/"

  devise_for :users,  controllers: {registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks", passwords: "users/passwords" }
  devise_for :organizers, controllers: {registrations: "organizers/registrations"}
  devise_for :admins

  match '/set_locale/:locale', to: 'application#set_locale_manually', via: 'get', as: :set_locale

  namespace :organizers, path: "organizer", shallow_path: "organizer" do
    resources :events do
      member do
        patch :publish
      end
    end
    resources :conferences, module: :events do
      member do
        get :present
      end
    end
  end

  resources :tags, only: [:index, :show]
  resources :questions, only: [:index], constraints: { token: /([a-z]|[0-9])+/i }
  resources :event_code_requests, only: [:new, :create] do
    collection do
      get :show
    end
  end

  get "pages/faq"
  get "pages/about"
  get "pages/features"

  get "dashboard" => "users#index"
  get ":id" => "users#show"

  root 'pages#landing'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  description  :text
#  created_at   :datetime
#  updated_at   :datetime
#  start_at     :datetime
#  end_at       :datetime
#  organizer_id :integer
#  logo         :string(255)
#  map_picture  :string(255)
#  city_id      :integer
#  status       :string(255)
#  token        :string(255)
#  timezone     :string(255)
#

class Event < ActiveRecord::Base
  include AASM
  include EventConcern
  belongs_to :organizer
  belongs_to :city

  has_many :event_users, dependent: :destroy
  has_many :conferences, dependent: :destroy
  has_many :indications, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :lecturers, through: :conferences # exclude from rails admin forms
  has_many :announces, dependent: :destroy
  has_many :attendees, -> { where(checkin: true) }, class_name: "EventUser"
  has_many :attendees_users, through: :attendees, class_name: "User", source: :user  # exclude from rails admin forms
  has_many :attending_users, through: :attendees, class_name: "User", source: :user
  accepts_nested_attributes_for :locations, allow_destroy: true
  accepts_nested_attributes_for :indications, allow_destroy: true, reject_if: proc { |attributes| attributes['content'].blank? }

  validates :name, presence: true
  validates :timezone, presence: true
  validates_length_of :description, maximum: 500, too_long: 500

  attr_accessor :set_location_to_all_confs

  acts_as_taggable rescue nil

  mount_uploader :logo, EventLogoUploader
  mount_uploader :map_picture, EventMapUploader

  aasm :column => 'status' do
    state :draft, :initial => true
    state :published

    event :publish do
      transitions :from => :draft, :to => :published, guard: :dates_already_set?
    end

    event :unpublish do
      transitions :from => :published, :to => :draft
    end
  end

  rails_admin do
    edit do
      exclude_fields :lecturers, :attendees, :attendees_users
    end
  end

  alias_method :attendants, :attendees

  def status_enum #TODO is this being used ever?
    [["Borrador", :draft], ["Publicado", :published]]
  end

  def dates_already_set?
    start_at.present? && end_at.present?
  end

  def attending
    event_users.where(rsvp: "yes")
  end

  def storage_url
    logo.present? ? "http://trendingconf.s3.amazonaws.com/" + logo.path : "images/logo_default.png"
  end

  def map_picture_url
    map_picture.present? ? "http://trendingconf.s3.amazonaws.com/" + map_picture.path : "images/logo_default.png"
  end

  def past?
    start_at.present? && start_at < Time.zone.now
  end

  def published?
    return true unless self.status != "published"
  end

  def in_time?(time = Time.zone.now)
    (start_at.blank? || end_at.blank?) ? false : (time >= start_at && time <= end_at)
  end

  def get_current_conferences
    now = Time.zone.now
    self.conferences.where("conferences.start_at <= ? AND conferences.end_at >= ? AND conferences.archived = ?", now, now, false)
  end

  def process_timezone
    self.start_at = Time.use_zone(self.timezone) { Time.zone.local_to_utc(self.start_at) } if (self.timezone.present? && self.start_at.present?)
    self.end_at = Time.use_zone(self.timezone) { Time.zone.local_to_utc(self.end_at) } if (self.timezone.present? && self.end_at.present?)
    return self
  end
end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,# :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events, dependent: :destroy
  has_many :conferences, through: :events

  validates :company_name, presence: true
end

# == Schema Information
#
# Table name: organizers
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  authentication_token   :string(255)
#  company_name           :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

app/controllers/concerns/organizers/events_concerns.rb
module Organizers::EventsConcerns
  extend ActiveSupport::Concern

  # This module is created in order to de-couple ROR from the business logic, making this easier to modify and organize

  # create event

  def create_event(organizer, event_params)
    event = organizer.events.new(event_params)
    event.process_timezone.save
    event
  end

  # update event
  def publish_or_unpublish(event, publish_signal, publish_token)
    case publish_signal
      when "publish"
        return publish_event(event, publish_token) if event.may_publish?
      when "unpublish"
        return unpublish_event(event) if event.may_unpublish?
      else
        return [:error, :unknown_action]
    end
  end

  def update_event(event, event_params)
    event.assign_attributes(event_params)
    if event.process_timezone.save
      location = event.locations.first
      if event_params[:set_location_to_all_confs] == "true"
        new_location_id = location.nil? ? nil : location.id
        event.conferences.update_all location_id: new_location_id
      end
      [:notice, :updated]
    else
      [:error, :not_updated]
    end
  end

  def publish_event(event, token)
    event_code = EventCode.find_by_token(token)
    if event_code.present? && event_code.active?
      ActiveRecord::Base.transaction do # It is perfectly fine to mix model types inside a single transaction block. This is because the transaction is bound to the database connection not the model instance.
        if event_code.event_id.present?
          return [:error, :code_already_used] if event_code.event_id != event.id
        else
          event_code.event_id = event.id
        end
        Time.use_zone(event.timezone) { event.publish! }
        event_code.deactivate!
        return [:notice, :published]
      end
    else
      [:error, :invalid_token]
    end
  end

  def unpublish_event(event)
    event_code = EventCode.find_by_event_id(event.id)
    if event_code.present? && event_code.inactive?
      ActiveRecord::Base.transaction do # Reffer to comment in publish_event
        Time.use_zone(event.timezone) { event.unpublish! }
        event_code.activate!
        return [:notice, :unpublished]
      end
    else
      [:error, :invalid_token]
    end
  end
end

app/controllers/organizers/events/conferences_controller.rb
class Organizers::Events::ConferencesController < ApplicationController
  before_filter :authenticate_organizer!
  before_action :set_conference, only: [:show, :edit, :update, :destroy, :present]
  before_action :set_event, only: [:new, :create]

  def new
    @conference = @event.conferences.new
    @locations  = @event.locations
    @conference.lecturers.build
    @countries = Country.all
  end

  def create
    @conference = @event.conferences.new(conference_params)
    unless @conference.archived
      if @conference.dates_not_set?
        @conference.archived = true
      end
    end
    respond_to do |format|
      if @conference.save #internally localize the dates in model concern
        format.html { redirect_to organizers_conference_path(@conference), success: 'Conference was successfully created.' }
        format.json { render action: 'show', status: :created, location: @conference }
      else
        format.html do
          @conference.assign_attributes(start_at: conference_params[:start_at], end_at: conference_params[:end_at]) #Set dates back to the user input
          @locations  = @event.locations
          @countries = Country.all
          render action: 'new'
        end
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @conference.assign_attributes(conference_params)
      if @conference.dates_not_set?
        @conference.archived = true
      end
      if @conference.save
        format.html { redirect_to [:organizers, @conference], success: 'Conference was successfully updated.' }
        format.json { head :no_content }
      else
        @conference.assign_attributes(start_at: conference_params[:start_at], end_at: conference_params[:end_at]) #Set dates back to the user input
        set_variables_for_edit_form
        format.html { render 'edit' }
        #format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
    set_variables_for_edit_form
  end

  def show
    @event = @conference.event
  end

  def present
    @event = @conference.event
  end

  def destroy
    @event = @conference.event
    @conference.destroy
    respond_to do |format|
      format.html { redirect_to organizers_event_path(@event) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conference
      @conference = current_organizer.conferences.find(params[:id])
    end

    def set_event
      @event = current_organizer.events.find(params[:event_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conference_params
      params.require(:conference).permit(:name, :description, :embedded_url, :location_id, :start_at, :end_at, :archived, :tag_list, lecturers_attributes: [:id, :name, :description, :linkedin_url, :country_id, :country_code, :_destroy])
    end

    def set_variables_for_edit_form
      @event = @conference.event
      @locations  = @event.locations
      @conference.lecturers.build if @conference.lecturers.empty?
    end

end

app/controllers/organizers/events_controller.rb
class Organizers::EventsController < ApplicationController
  include Organizers::EventsConcerns
  respond_to :html
  respond_to :json

  before_filter :authenticate_organizer!
  before_action :set_event, only: [:show, :edit, :update, :destroy, :publish]

  ##helper_method :dummy

  def index
    @current_events = current_organizer.events.where("start_at <= ? AND end_at >= ? AND status != ?", Time.zone.now, Time.zone.now, 'draft' ).page(params[:page]).per(20)
    @events = case params[:filter]
    when "previous"
      current_organizer.events.where("end_at < ? AND status != ?", Time.zone.now, 'draft').page(params[:page]).per(20)
    when "upcoming"
      current_organizer.events.where("start_at > ? AND status != ?", Time.zone.now, 'draft').page(params[:page]).per(20)
    else
      current_organizer.events.where("status = ?", 'draft').page(params[:page]).per(20)
    end

  end

  def new
    @event = current_organizer.events.new
    @event.locations.build
    # @event.indications.build
  end

  def show

    flash.now[:info] = "This event is happening right now." if (@event.in_time? && @event.published? )
    @current_conferences = @event.get_current_conferences
    now = Time.zone.now.utc
    @conferences = case params[:filter]
    when "previous"
      @event.conferences.where("start_at < ? AND end_at < ?  AND archived = ?", now, now, false).page(params[:page]).per(20).order("start_at ASC")
    when "upcoming"
      @event.conferences.where("start_at >= ? AND archived = ?", now, false).page(params[:page]).per(20).order("start_at ASC")
    else #when drafts
      @event.conferences.where("archived = ?", true).page(params[:page]).per(20).order("start_at ASC")
    end
  end

  def edit
    @event.indications.build unless @event.indications.present?
    @event.locations.build unless @event.locations.present?
  end

  def create
      @event = create_event(current_organizer, event_params)
      flash[:notice] = t("flash.actions.organizers.events.create.success") unless @event.id.blank?
      respond_with @event, location: new_organizers_conference_path(event_id: @event.id)
  end

  def update
    result, signal = update_event(@event, event_params)
    flash[result] = t("flash.actions.organizers.events.update.#{signal}") 
    respond_with @event, location: [:organizers, @event]
  end

  def publish
    begin
      if params[:publish].present?
        result, signal = publish_or_unpublish(@event, params[:publish], params[:token])
        flash[result] = t("flash.actions.organizers.events.publish.#{signal}") 
        respond_with @event, location: [:organizers, @event]
      end
    rescue 
      flash[:error] = t("flash.actions.organizers.events.publish.exception") 
      respond_with @event, location: [:organizers, @event]
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to organizers_events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      begin
        @event = current_organizer.events.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:error] = "The event you tried to reach is NOT of yours! This incident will be reported." #TODO
        redirect_to action: :index
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :set_location_to_all_confs, :timezone, :logo, :map_picture, :description,
        :start_at, :end_at, :tag_list, locations_attributes: [:id, :name, :address,
        :latitude, :longitude, :_destroy], indications_attributes: [:id, :content,
          :kind, :_destroy] ) if params[:event].present?
    end
end

app/controllers/organizers/registrations_controller.rb
class Organizers::RegistrationsController < Devise::RegistrationsController

  protected

    def after_update_path_for(resource)
      organizers_events_path
    end

end

app/helpers/events_helper.rb
module EventsHelper

	def insert_date_of (conference, message_4_missing)
		Time.use_zone(conference.event.timezone) do
			context = 'views.organizers.events.show'
			return message_4_missing unless conference.start_at.in_time_zone.present?

			days_of_difference = (conference.start_at.day-conference.end_at.day) / 1.day
			if days_of_difference == 0
				return t("#{context}.conferences_list.date.days", :count => days_of_difference,
	              start_time: l(conference.start_at.in_time_zone, format: :conference_start_time_same_day),
	              end_time: l(conference.end_at.in_time_zone, format: :conference_end_time_same_day))
			else
				return t("#{context}.conferences_list.date.days", :count => days_of_difference,
	              start_time: l(conference.start_at.in_time_zone, format: :conference_start_time_different_day),
	              end_time: l(conference.end_at.in_time_zone, format: :conference_end_time_different_day))
			end
		end unless (conference.start_at.blank? || conference.end_at.blank?)
	end

  def filter_active_tab(value)
    return "active" if (value === "drafts" && params[:filter].blank?) || value === params[:filter]
  end
end

app/helpers/organizers/events/conferences_helper.rb
module Organizers::Events::ConferencesHelper
  GooglePattern = /(docs.google.com\/presentation\/d\/\w+)/i
  def presentation_url(conference)
    case
    when conference.embedded_url.match(GooglePattern)
      url = "https://#{$1}/embed?start=true&loop=false&delayms=100000&micefySignal=start&micefyId=#{conference.id}&micefyHash=#{conference.security_hash}"
      url += "&micefyDev=true" if Rails.env.development?
      url
    else
      conference.embedded_url
    end
  end
end

app/views/organizers/events/edit.html.erb
<% context = 'views.organizers.events.edit'%>
<h1><%= t("#{context}.title") %></h1>
<%= render 'form' %>

app/views/organizers/events/new.html.erb
<% context = 'views.organizers.events.new' %>
<h1><%= t("#{context}.title") %></h1>

<%= render 'form' %>

<%= link_to t("#{context}.back"), organizers_events_path %>

app/views/organizers/events/show.html.erb
<% context = 'views.organizers.events.show'%>
<% unless @event.published? %>
  <div class="bg-warning">
    <div class="row">
      <div class="col-xs-6">
        <p><%= t("#{context}.not_published") %></p>
      </div>
      <div class="col-xs-6">
        <%= link_to t("#{context}.publish_button"), "#publish", class: "btn btn-success btn-lg pull-right", :"data-toggle" => "modal" %>
      </div>
    </div>
  </div>
<% end %>
<div class="page-header row">
  <div class="pull-left event-title" >
    <h1 ><%= @event.name %></h1>
  </div>
  <div class="pull-right">
    <% if @event.logo.blank? %>
      <% placeholder_url= "http://placehold.it/270x90&text="+t("#{context}.logo.placeholder_message") %>
      <%= link_to edit_organizers_event_path(@event) do%>
        <%= image_tag(placeholder_url, class: "img-responsive", alt: "Upload Logo")%>
      <% end %>
    <% else %>
      <%= image_tag(@event.logo.url, class: "img-responsive", alt: "Upload Logo" ) %>
    <% end %>
  </div>
</div>


<% if @event.in_time? %>
  <div id="current-conferences" class="panel panel-primary">
    <div class="panel-heading">
      <h2 class="panel-title"><%= t("#{context}.current_conferences.title")%></h2>
    </div>
    <% if @current_conferences.length > 0 %>
      <table class="table">
        <% @current_conferences.each do |conference| %>
          <tr>
            <td>
              <% if conference.in_time? %>  
                <div class="pull-left">
                  <h4 style="vertical-align: middle">
                    <a ><%= link_to conference.name, organizers_conference_path(conference) %></a>
                  </h4>
                </div>
                <div class="pull-right">
                  <%= link_to( t("#{context}.current_conferences.present"), present_organizers_conference_path(conference), class: "btn btn-success" )  unless ( conference.embedded_url.nil? || conference.embedded_url.empty? || !@event.published? )  %>
                  <%= link_to t("#{context}.current_conferences.questions"), questions_path(token: @event.token), class: "btn btn-success", target: "_blank", disabled: "disabled" if @event.may_publish? %>
                </div>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <div class="panel-body" >
        <%= t("#{context}.current_conferences.no_conferences_msg")%>
      </div>
    <% end %>
  </div>
<% end %>

<h2><%= t("#{context}.information_subtitle") %></h2>
<div class="panel panel-default">
  <div class="panel-heading"><h4><%= t("#{context}.duration.subtitle")%></h4></div>
  <div class="panel-body">
    <% Time.use_zone(@event.timezone || "UTC") do %>
      <% if @event.start_at.present? && @event.end_at.present? && @event.start_at.month == @event.end_at.month %>
        <b><%= t("#{context}.duration.from")%></b>
        <%= l @event.start_at.in_time_zone, format: :event_start_date_same_month %>
        <b> <%= t("#{context}.duration.to")%></b>
        <%= l @event.end_at.in_time_zone, format: :event_end_date_same_month %>
      <% elsif @event.start_at.present? && @event.end_at.present? %>
        <b><%= t("#{context}.duration.from")%></b>
        <%= l @event.start_at.in_time_zone, format: :event_different_month %>
        <br/>
        <b> <%= t("#{context}.duration.to")%></b>
        <%= l @event.end_at.in_time_zone, format: :event_different_month %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><h4><%= t("#{context}.description.subtitle")%></h4></div>
  <div class="panel-body">
    <%= @event.description %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><h4><%= t("#{context}.locations.subtitle")%></h4></div>
  <ul class="list-group">
   	<% @event.locations.each do |location| %>
      <li class="list-group-item">
        <span><%= "#{location.name}, #{location.address}" %></span>
        <div>
          <img src='<%= "http://maps.google.com/maps/api/staticmap?zoom=15&size=400x400&maptype=roadmap&markers=color:blue|label:S|#{location.latitude},#{location.longitude}" %>'>
        </div>
      </li>
  	<% end %>
  </ul>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><h4><%= t("#{context}.twitter.subtitle")%></h4></div>
  <div class="panel-body">
    <% if @event.tag_list.empty? %>
      <%= t("#{context}.twitter.not_present")%>
    <% else %>
      <% @event.tag_list.each do |tag| %>
        <%= "##{tag}" %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><h4><%= t("#{context}.indications.subtitle")%></h4></div>
  <table class="table">
    <% if @event.indications.blank? %>
      <div class="panel-body">
        <%= t("#{context}.indications.not_present")%>
      </div>
    <% else %>
      <% @event.indications.each do |indication| %>
        <% case indication.kind %>
          <% when "information" %>
            <tr class="success">
              <td><%= t("#{context}.indications.information")%></td>
              <td><%= "#{indication.content}" %></td>
            </tr>
          <% when "warning" %>
            <tr class="warning">
              <td><%= t("#{context}.indications.warning")%></td>
              <td><%= "#{indication.content}" %></td>
            </tr>
          <% when "regulatory" %>
            <tr class="danger">
              <td><%= t("#{context}.indications.regulatory")%></td>
              <td><%= "#{indication.content}" %></td>
            </tr>
        <% end %>
      <% end %>
    <% end %>
  </table>
</div>

<%= link_to t("#{context}.edit_button"), edit_organizers_event_path(@event), class: "btn btn-primary btn-lg" %>
<% if (@event.published?)%>
  <%= button_to t(".publish_button", default: "Des-Publicar"), publish_organizers_event_path(@event) + "?publish=unpublish", class: "btn btn-danger btn-lg", method: :patch %>
<% else %>
<!--   <%= link_to t(".publish_button", default: "Publicar"), "#publish", class: "btn btn-success btn-lg", :"data-toggle" => "modal" %> -->
  <div class="modal fade" id="publish">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title">Publicar</h4> <!-- TODO -->
        </div>
        <%= form_tag publish_organizers_event_path, method: :patch do %>
          <div class="modal-body">
            <%= hidden_field_tag :publish, "publish" %>
            <%= label_tag :token %>
            <%= text_field_tag :token %>
            <br/>
            <div class="clearfix">
              <%= link_to t(".request_token", scope: "views"), new_event_code_request_path %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= submit_tag "Save Changes", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
<% end %>

<hr/>


<h2><%= t("#{context}.conferences_title")%></h2>
<ul class="nav nav-tabs" id="conference-tabs">
  <li class="<%= filter_active_tab("upcoming") %>">
    <%= link_to t("#{context}.upcoming"), "?filter=upcoming#conference-tabs" %>
  </li>
  <li class="<%= filter_active_tab("previous") %>">
    <%= link_to t("#{context}.previous"), "?filter=previous#conference-tabs" %>
  </li>
  <li class="<%= filter_active_tab("drafts") %>">
    <%= link_to t("#{context}.drafts"), "?filter=drafts#conference-tabs" %>
  </li>
  <div>
    <li class="pull-right">
    <%= link_to t("#{context}.new"), new_organizers_conference_path(event_id: @event.id), class: "btn btn-primary btn-sm" %></li>
  </div>
</ul>
<div class="list-group">
  <% if @conferences.empty? %>
    <div class="list-group-item">
      <small><%= t("#{context}.not_conferences")%></small>
    </div>
  <% end %>
  <% @conferences.each do |conference| %>
    <div class="list-group-item">

        <div class="col-10">
          <div>
          <h3 class="title-with-controls"><%= link_to conference.name, [:organizers, conference] %></h3>
          <div class="controls">

          <%= link_to edit_organizers_conference_path(conference), class: "action" do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
          <%= link_to [:organizers, conference], method: :delete, data: { confirm: 'Are you sure?' }, class: "action" do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        </div>
        </div>
          <small class="clearfix">
            <b><%=  t("#{context}.conferences_list.place.label") %>:</b>
            <% if conference.location.present? %>
              <%= "#{conference.location.name}, #{conference.location.address}"  %>
            <% else %>
              <%=  t("#{context}.conferences_list.place.empty") %>
            <% end %>
          </small>
          <small>
            <b><%=  t("#{context}.conferences_list.date.label") %>:</b>
            <%= insert_date_of conference, t("#{context}.conferences_list.date.empty") %>
          </small>
      </div>
    </div>
  <% end %>
  <br/>
  <%= link_to organizers_events_path, class: "btn btn-info btn-sm" do%>
    <span class="glyphicon glyphicon-arrow-left"> <%= t("#{context}.back") %></span>
  <% end %>
</div>