config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/mngmnt', :as => 'rails_admin'
  mount API => "/"

  devise_for :users,  controllers: {registrations: "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks", passwords: "users/passwords" }
  devise_for :organizers, controllers: {registrations: "organizers/registrations"}
  devise_for :admins

  match '/set_locale/:locale', to: 'application#set_locale_manually', via: 'get', as: :set_locale

  namespace :organizers, path: "organizer", shallow_path: "organizer" do
    resources :events do
      member do
        patch :publish
      end
    end
    resources :conferences, module: :events do
      member do
        get :present
      end
    end
  end

  resources :tags, only: [:index, :show]
  resources :questions, only: [:index], constraints: { token: /([a-z]|[0-9])+/i }
  resources :event_code_requests, only: [:new, :create] do
    collection do
      get :show
    end
  end

  get "pages/faq"
  get "pages/about"
  get "pages/features"

  get "dashboard" => "users#index"
  get ":id" => "users#show"

  root 'pages#landing'
end

app/views/layouts/application.html.erb
<% context = 'layouts.application'%>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= content_for?(:title) ? yield(:title) : "Micefy" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= yield(:scripts) %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div id="wrap">
      <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div><!-- /navbar -->

      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->
      </div> <!-- /container -->
    </div><!-- /wrap -->
    <footer>
      <div class="container">
        <p>&copy; MICE Technologies LLC 2014</p>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/pages.html.erb
<% context = 'layouts.pages'%>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Micefy" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <div id="wrap">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <% if signed_in? && organizer_signed_in? %>
              <%= link_to organizers_events_path, class: "navbar-brand" do %>
                <h3>Micefy <small>beta</small></h3>
              <% end %>
            <% else %>
              <%= link_to root_path, class: "navbar-brand" do %>
                <h3>Micefy <small>beta</small></h3>
              <% end %>
            <% end %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to(image_tag("", :alt => "", :class =>"flag flag-co"), set_locale_path(:es))  %></li>
              <li><%= link_to(image_tag("", :alt => "", :class =>"flag flag-us"), set_locale_path(:en))  %></li>
              <% if signed_in? %>
                <% if organizer_signed_in? %>
                  <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li>
                        <%= link_to('Edit', edit_organizer_registration_path) %>
                      </li>
                      <li>
                        <%= link_to('Sign out', destroy_organizer_session_path, :method => :delete) %>
                      </li>
                    </ul>
                  </li>
                <% elsif user_signed_in? %>
                  <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li>
                        <%= link_to('Edit', edit_user_registration_path) %>
                      </li>
                      <li>
                        <%= link_to('Sign out', destroy_user_session_path, :method => :delete) %>
                      </li>
                    </ul>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <%= bootstrap_flash %>
          </div>
        </div>
      </div><!-- /container flash-->
      <%= yield %>
    </div><!-- /wrap -->
    <footer>
      <div class="container">
        <p>&copy; MICE Technologies LLC 2014</p>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/questions.html.erb
<% context = 'layouts.pages'%>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Micefy" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <div id="wrap">
      <div class="container-fluid"> 
      <div class="navbar navbar-default navbar-fixed-top">
        <div class="centered">
          <%= link_to '/' do %>
            <h3>Micefy <small>beta</small></h3>
          <% end %>
        </div>
      </div><!-- /navbar -->

      <%= yield %>
     </div><!-- /wrap -->
     </div>
    <footer>
      <div class="centered">
        <p>&copy; MICE Technologies LLC 2014</p>
      </div>
    </footer>
  </body>
</html>